name: Compile for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gettext
      - name: Build
        run: |
          # 1. 运行 vendor 脚本，下载缺失的 sqlite3ext.h 等头文件
          chmod +x ./scripts/vendor.sh
          ./scripts/vendor.sh
          
          # 2. 生成头文件
          make sqlite-vec.h
          
          # 3. Use Android NDK 进行交叉编译
          export CC=${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang
          $CC -O3 -fPIC -shared sqlite-vec.c -o vec0.so -I. -Ivendor
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-vec-android
          path: vec0.so
