name: Compile for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext clang
      - name: Build
        run: |
          # 显式生成头文件
          make sqlite-vec.h
          
          # 明确使用 clang 编译生成加载库
          make loadable CC=clang
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-vec-android
          path: dist/
